djbook_test/apps/articles/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views, rest_views

app_name = 'articles'


router = routers.DefaultRouter()
router.register(r'articles', rest_views.ArticlesViewSet)
router.register(r'comments', rest_views.CommentsViewSet)
router.register(r'tags', rest_views.TagsViewSet)
router.register(r'votes', rest_views.VotesViewSet)
router.register(r'choices', rest_views.ChoicesViewSet)
router.register(r'article_likes', rest_views.ArticleLikeViewSet)
router.register(r'comment_likes', rest_views.CommentLikeViewSet)


urlpatterns = [
    path('api-root/', include(router.urls), name='api-root'),
    path('personal_page/', views.personal_page, name='personal_page'),
    path('', views.ArticleIndexView.as_view(), name='index'),
    path('<int:tag_id>/', views.TagListView.as_view(), name='tag'),
    path('my_articles/', views.MyArticlesView.as_view(), name='my_articles'),
    path('<int:pk>', views.ArticleDetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.VoteResultView.as_view(), name='results'),
    path('article_like/<int:article_id>/<int:like>', views.article_like, name='article_like'),
    path('comment_like/<int:comment_id>/<int:like>', views.comment_like, name='comment_like'),
    path('<int:article_id>/vote/', views.vote, name='vote'),
    path('<int:article_id>/comment_create/', views.CommentCreate.as_view(), name='comment_create'),
    path('<int:article_id>/<int:comment_id>/comment_edit/', views.CommentCreate.as_view(), name='comment_edit'),
    path('<int:article_id>/<int:comment_id>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('add_article/', views.article_create_update_form, name='article_create'),
    path('add_article/create_article/', views.article_db_save, name='article_create_save'),
    path('edit_article/<int:article_id>', views.article_create_update_form, name='article_update'),
    path('edit_article/<int:article_id>/article_delete/', views.article_db_save, name='article_update_save'),
    path('search/', views.ArticleSearchView.as_view(), name='search'),
    path('delete_article/<int:article_id>', views.article_delete, name='article_delete'),
    path('<int:article_id>/publish_article/', views.publish_article, name='publish_article'),
    # path('froala_form', views.froala_form, name='froala_form'),
    # path('post_froala_form', views.post_froala_form, name='post_froala_form'),
    # path('froala_index', views.FroalaIndexView.as_view(), name='froala_index'),
    # path('froala/<int:pk>/', views.FroalaDetailMixinView.as_view(), name='froala_detail'),
    # path('ajax_demo/', views.AjaxHandlerView.as_view(), name='ajax_demo'),
    # path('ajax_page/', views.ajax_page, name='ajax_page'),
    # path('ajax_check/', views.AjaxDataCheck.as_view(), name='ajax_check')
]

djbook_test/apps/home/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('language_switch/<str:user_language>/', views.lang_switcher, name='lang'),
]

djbook_test/apps/weather/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.weather, name='index'),
    path('get_weather/', views.get_weather, name='get_weather')
]

djbook_test/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/articles/images/favicon.ico'), name='favicon'),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('articles/', include('articles.urls')),
    path('weather/', include('weather.urls')),
    path('', include('home.urls')),
    path('admin228/', admin.site.urls, name='admin'),
    path('account/', include('allauth.urls')),
    path('avatar/', include('avatar.urls')),
    path('api/drf-auth/', include('rest_framework.urls')),
    path('api/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
)

if 'rosetta' in settings.INSTALLED_APPS and settings.DEBUG:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

djbook_test/apps/articles/models.py
from datetime import timedelta

from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Tag(models.Model):
    name = models.CharField(
        _('tag name'),
        max_length=200,
        validators=[
            MinLengthValidator(2),
            MaxLengthValidator(200)
        ]
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')


class Article(models.Model):
    title = models.CharField(
        _('article title'),
        max_length=200,
        unique=True,
        validators=[
            MinLengthValidator(5),
            MaxLengthValidator(200)
        ]
    )
    text = models.TextField(
        _('article text'),
        max_length=9000,
        validators=[
            MinLengthValidator(10),
            MaxLengthValidator(9000)
        ]
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(_('publication date'), auto_now_add=True, null=False)
    tag = models.ManyToManyField(Tag, blank=True)
    up_date = models.DateTimeField(_('updating date'), null=True, blank=True)
    is_published = models.BooleanField(_('is published'), null=False, default=False)
    like_count = models.PositiveIntegerField(_('like counter'), default=0)

    def __str__(self):
        return self.title

    def was_published_recently(self):
        now = timezone.now()
        return now - timedelta(days=1) <= self.pub_date <= now

    def publish(self):
        self.is_published = not self.is_published
        self.save()

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = _('Published recently?')

    class Meta:
        verbose_name = _('Article')
        verbose_name_plural = _('Articles')


class ArticleLike(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_like = models.BooleanField(_('is like'))

    class Meta:
        verbose_name = _('Article like')
        verbose_name_plural = _('Article like')


class Choice(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    text = models.CharField(
        max_length=200,
        validators=[
            MinLengthValidator(2),
            MaxLengthValidator(200)
        ]
    )
    votes = models.PositiveIntegerField(_('votes'), default=0)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = _('Choice')
        verbose_name_plural = _('Choices')


class Vote(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Vote')
        verbose_name_plural = _('Votes')


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)  # Foreignkey binding to the Article class,
    # when the Article is removed, the Comment assigned to it is removed
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(
        _('comment text'),
        max_length=300,
        blank=False,
        validators=[
            MinLengthValidator(4),
            MaxLengthValidator(300)
        ]
    )
    pub_date = models.DateTimeField(_('publication date'), auto_now_add=True)
    up_date = models.DateTimeField(_('updating date'), null=True, default=None)
    like_count = models.PositiveIntegerField(_('like counter'), default=0)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')


class CommentLike(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_like = models.BooleanField(_('is like'))

    class Meta:
        verbose_name = _('Comment like')
        verbose_name_plural = _('Comment likes')


'''
class Folder(models.Model):
    name = models.CharField('folder name', max_length=150)
    owner = models.CharField('user name', max_length=150)
    users = ArrayField(models.IntegerField())  # Users who have access


class File(models.Model):
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    file_name = models.CharField('file name', max_length=255)
    file_hash = models.CharField(max_length=32, editable=False)
    upload_date = models.DateTimeField('date uploadnig')
    storage = models.FileField(upload_to='configurations',storage=file_storage, unique=True)

    def save(self, *args, **kwargs):
        self.file_hash = md5(self.file_name.encode()).hexdigest()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.file_name
'''


'''
class FroalaModel(models.Model):
    name = models.CharField('Froala name', max_length=200)
    content = FroalaField()
    date = models.DateTimeField('Create data', auto_now=True)
'''


'''
from django.contrib.postgres.fields import ArrayField
from storages.backends.sftpstorage import SFTPStorage
from hashlib import md5

file_storage = SFTPStorage()
'''


'''
from avatar import models as avatar_models

def validate_file_size(value, max_size=5):
    max_size = max_size * 1024 * 1024
    filesize = value.size
    if filesize > max_size:
        raise ValidationError("The maximum file size that can be uploaded is 5MB.")


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = avatar_models.Avatar()
    avatar = models.ImageField(upload_to='profile_pic/', default='articles/images/user_default.png',
                               validators=[validators.FileExtensionValidator(['jpg', 'jpeg', 'png']),
                                           validate_file_size])
'''

djbook_test/apps/home/models.py
from django.db import models
from django.contrib.auth.models import User


class GuestData(models.Model):
    user = models.CharField(max_length=100)
    device = models.TextField()
    address = models.TextField()
    date = models.DateTimeField(auto_now_add=True, null=False)

djbook_test/apps/weather/models.py
from django.db import models

# Create your models here.

djbook_test/apps/articles/forms.py
from django import forms
from django.utils.translation import gettext as _
import re

from .models import Comment, Article


def cleanhtml(raw_html):
    clean_re = re.compile('<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});')
    cleantext = re.sub(clean_re, '', raw_html)
    return cleantext


def text_validator(origin_text: str, min_length: int = 0, max_length: int = 0):

    splitted_text: list = cleanhtml(origin_text.strip()).split()
    formated_text = ' '.join(splitted_text)
    if min_length:
        if not len(formated_text) >= min_length:
            return ''
    if max_length:
        if not len(formated_text) <= max_length:
            return ''
    if len(splitted_text) > 0 and not formated_text.isspace():
        return origin_text.strip()
    else:
        return ''


class CommentForm(forms.ModelForm):
    """Comments form"""

    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'cols': 45,
                                          'rows': 3,
                                          'minlength': 4,
                                          'maxlength': 300,
                                          'placeholder': _('Your comment...')})
        }
        labels = {
            'text': '',
        }


class ArticleEditForm(forms.ModelForm):
    """Add article form"""

    class Meta:
        model = Article
        fields = ('title', 'text')
        widgets = {
            'title': forms.TextInput(attrs={'minlength': 5,
                                            'maxlength': 200}),
            'text': forms.Textarea(attrs={'minlength': 10,
                                          'maxlength': 9000})
        }

djbook_test/apps/home/views.py
from os import getenv
from urllib.parse import urlparse, urlunparse

import ipinfo
from django.shortcuts import render, redirect
from django.utils.translation import activate
from .models import GuestData


def user_checker(address):
    access_token = getenv('ADDR_CHECK_API')
    handler = ipinfo.getHandler(access_token)
    details = handler.getDetails(address)
    return details.all


def get_address(request):
    if 'HTTP_X_FORWARDED_FOR' in request.META:
        address = request.META['HTTP_X_FORWARDED_FOR']
        return address
    else:
        return request.META['REMOTE_ADDR']


def home(request):
    user = request.user
    device_data = request.META
    address = get_address(request)
    address_data = user_checker(address)
    new = GuestData(user=user, device=device_data, address=address_data)
    new.save()
    return render(request, 'home/home_page.html')


def about(request):
    return render(request, 'home/about.html')


def lang_switcher(request, user_language):
    activate(user_language)
    # Redirect the user back to the previous page
    parsed_url = list(urlparse(request.META.get('HTTP_REFERER')))
    path_parts = parsed_url[2].split('/')
    path_parts[1] = user_language
    parsed_url[2] = '/'.join(path_parts)
    response = redirect(urlunparse(parsed_url))
    response.set_cookie('django_language', user_language)
    return response  # redirect(urlunparse(parsed_url))

djbook_test/apps/weather/views.py
import requests
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib.humanize.templatetags import humanize
from datetime import datetime
from os import getenv


def weather(request):
    return render(request, 'weather/weather_page.html')


API_KEY = getenv('OPENWEATHER_API')
BASE_URL = 'https://api.openweathermap.org/data/2.5/forecast'


def process_forecast_data(data):
    filtered_forecast = []
    last_data = ''

    for item in data['list']:
        date_time_obj = datetime.strptime(item['dt_txt'], "%Y-%m-%d %H:%M:%S")
        humanized_date = humanize.naturalday(date_time_obj)

        if humanized_date == last_data:
            humanized_date = ''
        else:
            last_data = humanized_date

        element = {
            'day': humanized_date,
            'time': date_time_obj.strftime("%H:%M"),
            'temperature': round(item['main']['temp'], 1),
            'wind': round(item['wind']['speed'], 1),
            'description': item['weather'][0]['description']
        }

        filtered_forecast.append(element)

    return filtered_forecast


def get_weather(request):
    if request.method == 'POST':
        lat = request.POST.get('lat')
        lng = request.POST.get('lng')

        if not lat or not lng:
            return JsonResponse({'error': 'Latitude and longitude are required'}, status=400)

        params = {
            'lat': lat,
            'lon': lng,
            'appid': API_KEY,
            'units': 'metric'
        }

        forecast_response = requests.get(BASE_URL, params=params)

        if forecast_response.status_code != 200:
            return JsonResponse({'error': 'Invalid request method'}, status=400)

        forecast_data = forecast_response.json()
        filtered_forecast = process_forecast_data(forecast_data)

        location = forecast_data['city'][
                       'name'] or f'{forecast_data["city"]["coord"]["lat"]}, {forecast_data["city"]["coord"]["lon"]}'
        weather_info = f'<h2>Location: {location}</h2>'

        ready_forecast = '<table><colgroup span="4"></colgroup><tr><th>Day</th><th>Time</th><th>Temperature</th><th>Wind</th><th>Weather</th></tr>'

        for item in filtered_forecast:
            info = f'<tr><td>{item["day"]}</td>'
            info += f'<td>{item["time"]}</td>'
            info += f'<td>{item["temperature"]} C</td>'
            info += f'<td>{item["wind"]} m/s</td>'
            info += f'<td>{item["description"]}</td></tr>'
            ready_forecast += info

        ready_forecast += '</table>'

        return JsonResponse({'weather_info': weather_info, 'forecast': ready_forecast})

    return JsonResponse({'error': 'Invalid request method'}, status=400)

djbook_test/templates/articles/article_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load l10n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'articles/css/article_list.css' %}">
{% endblock %}

{% block head_title %}
	{% translate 'Articles' %}
{% endblock %}

{% block content %}
<div class="main">

        {% if user.is_staff %}
            {% if user.is_authenticated %}
                <a href="{% url 'articles:article_create' %}" class="add_article"> + {% translate 'Add article' %}</a>
            {% else %}
                <p class="add_article">
                    {% translate 'For add article you need to' %}
                    <a href="/accounts/login/">{% translate 'Sign In' %}</a>
                </p>
            {% endif %}
        {% endif %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if my_article_list %}
        <h3>{% translate 'My articles' %}:</h3>
    {% elif search_list %}
        <h3>{% translate 'Search results' %}:</h3>
    {% elif tags_list %}
        <h3>{% translate 'Tag results' %}:</h3>
    {% else %}
        <h3>{% translate 'Articles' %}:</h3>
    {% endif %}

    <ul>
        {% if error_message %}
		    <p><strong>
                {{ error_message }}
                {% if not user.is_authenticated %}
                    <a href={% url 'account_login' %}>Sign In</a>
                {% endif %}
            </strong></p>
	    {% endif %}
            {% if my_article_list %}
                {% for article in my_article_list %}
                    <li>
                        <a href="{% url 'articles:detail' article.id %}">{{ article.title }}</a> |
                        <a href="{% url 'articles:article_update' article.id %}"> {% translate 'Edit' %}</a> |
                        <a href="{% url 'articles:article_delete' article.id %}"> {% translate 'Delete'%}</a>
                    </li>
                {% empty %}
                    <p>{% translate 'No articles are available' %}.</p>
                {% endfor %}
            {% else %}
                {% for article in page_obj %}
                    <li>
                        {% if user.is_superuser %}
                            {% if article.is_published %}
                                <a href="{% url 'articles:publish_article' article.id %}"> {% trans 'Unpublish' %}</a>
                            {% else %}
                                <a href="{% url 'articles:publish_article' article.id %}"> {% trans 'Publish' %}</a>
                            {% endif %}
                            |
                        {% endif %}
                        <a href="{% url 'articles:detail' article.id %}">{{ article.title }}</a>
                    </li>
                {% empty %}
                    <p>{% translate 'No articles are available' %}.</p>
                {% endfor %}
            {% endif %}
    </ul>
</div>
<div class="pagination">
    <span class="step-links">
    {% if page_obj.number %}
        {% if page_obj.has_previous %}
            {% if request.GET.search %}

                <a href="?search={{ request.GET.search}}&page=1">&laquo; {% translate 'First' %}</a>
                {% if page_obj.previous_page_number != 1 %}
                    <a href="?search={{ request.GET.search}}&page={{ page_obj.previous_page_number }}">{% translate 'Previous' %}</a>
                {% endif %}

            {% else %}

                <a href="?page=1">&laquo; {% translate 'First' %}</a>
                {% if page_obj.previous_page_number != 1 %}
                    <a href="?page={{ page_obj.previous_page_number }}">{% translate 'Previous' %}</a>
                {% endif %}

            {% endif %}

        {% endif %}

        <span class="current">
            {% translate 'Page' %} {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            {% if request.GET.search %}

                <a href="?search={{ request.GET.search}}&page={{ page_obj.next_page_number }}">{% translate 'Next' %}&nbsp;&raquo;</a>
                {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
                    <a href="?search={{ request.GET.search}}&page={{ page_obj.paginator.num_pages }}">{% translate 'Last' %}&raquo;</a>
                {% endif %}

            {% else %}

                <a href="?page={{ page_obj.next_page_number }}">{% translate 'Next' %}&nbsp;&raquo;</a>
                {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
                    <a href="?page={{ page_obj.paginator.num_pages }}">{% translate 'Last' %} &raquo;</a>
                {% endif %}

            {% endif %}
        {% endif %}
    {% endif %}
    </span>
</div>
{% endblock %}

djbook_test/templates/articles/home_page.html
{% extends 'articles/base.html' %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %}
	RODJER | {% translate 'Home' %}
{% endblock %}

{% block content %}
<div class="main">
	{% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'articles/css/home_style.css' %}">

    <a href="{% url 'articles:index' %}"><h1>{% translate 'Articles' %}</h1></a>
    <a href="{% url 'articles:about' %}"><h1>{% translate 'About' %}</h1></a>

</div>
{% endblock %}

djbook_test/templates/articles/navbar.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href={% url 'articles:home' %}>RODGER</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href={% url 'articles:index' %}>{% translate 'Articles' %}</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {% translate 'My Account' %}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            {% if user.is_superuser %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">{{ user.username }}</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'articles:personal_page' %}">{{ user.username }}</a></li>
                            {% endif %}
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'account_email' %}">{% translate 'Email settings' %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'account_logout' %}">{% translate 'LogOut' %}</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'articles:api-root' %}" target="_blank">{% translate 'API Root' %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'login' %}" target="_blank">{% translate 'Get API Key' %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}" target="_blank">{% translate 'Delete API KEY' %}</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'account_login' %}">{% translate 'LogIn' %}</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'account_signup' %}">{% translate 'Register Now' %}</a></li>
                        {% endif %}
                    </ul>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href='{% url 'articles:article_create' %}'>{% translate 'Add article' %} +</a>
                    </li>
                {% endif %}
                <a class="nav-link" href={% url 'articles:about' %}>About</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ LANGUAGE_CODE }}
                    </a>
                    {% get_available_languages as languages %}
                    {% get_language_info_list for languages as lang_info %}
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for lang in lang_info %}
                            {% language lang.code %}
                                <li><a class="dropdown-item" href="{% url 'articles:lang' lang.code %}">{{ lang.name_local }}</a></li>
                            {% endlanguage %}
                        {% endfor %}
                    </ul>
                </li>
            </ul>
            <form class="d-flex" action="{% url 'articles:search' %}" method="get">
                <input name="search" class="form-control me-2" type="search" minlength="3" placeholder={% translate "Search" %} aria-label="Search" required>
                <button class="btn btn-outline-success" type="submit">{% translate 'Search' %}</button>
                {{ search_message }}
            </form>
        </div>
    </div>
</nav>

djbook_test/templates/articles/personal_page.html
{% extends 'base.html' %}
{% load i18n %}
{% load avatar_tags %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/home_style.css' %}">
{% endblock %}

{% block head_title %}
	{% translate 'Personal page' %}
{% endblock %}

{% block content %}
<div class="main">




<div style="float: left; width: 50%;">
    <h1>Avatar:</h1>

    {% avatar user %}


        <a href="{% url 'avatar_add' %}"><h1>{% translate 'Add Avatar' %}</h1></a>
        <a href="{% url 'avatar_change' %}"><h1>{% translate 'Change Avatar' %}</h1></a>
        <a href="{% url 'avatar_delete' %}"><h1>{% translate 'Delete Avatar' %}</h1></a>
</div>
<hr>
<div style="margin-left: 50%; width: 50%;">
<a href="{% url 'articles:my_articles' %}"><h1>{% translate 'My Articles' %}</h1></a>
</div>


</div>
{% endblock %}

djbook_test/templates/articles/testing_page.html
{% extends 'base.html' %}

{% block head_title %}
	RODJER | Test
{% endblock %}

{% block content %}
<div class="main">
	{% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'articles/css/article_list.css' %}">

    <p>Title: {{ title }}</p>
    <p>Text: {{ text }}</p>
    {% if option %}
        {% for i in option %}
            <p>Option: {{ i }}</p>
        {% endfor %}
    {% endif %}
    <p>Test message: {{ test }}</p>

</div>
{% endblock %}

djbook_test/templates/articles/votes_results.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'articles/css/votes_results.css' %}">
{% endblock %}

{% block head_title %}
	{% trans 'Results' %} | {{ article.title }}
{% endblock %}

{% block content %}
<div class="content">



	<h1>{{ article.title }}</h1>

	<ul>
		{% for choice in article.choice_set.all %}
			<li>{{ choice.text }} {% translate 'have' %} {{ choice.votes }} {% translate 'vote' %}{{ choice.votes|pluralize }}</li>
		{% endfor %}
	</ul>
	{% block nav-results %}<a href="{% url 'articles:detail' article.id %}" class="again">{% translate 'Back to Question page' %}?</a>{% endblock %}
</div>
{% endblock %}