djbook_test/apps/articles/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views, rest_views

app_name = 'articles'


router = routers.DefaultRouter()
router.register(r'articles', rest_views.ArticlesViewSet)
router.register(r'comments', rest_views.CommentsViewSet)
router.register(r'tags', rest_views.TagsViewSet)
router.register(r'votes', rest_views.VotesViewSet)
router.register(r'choices', rest_views.ChoicesViewSet)
router.register(r'article_likes', rest_views.ArticleLikeViewSet)
router.register(r'comment_likes', rest_views.CommentLikeViewSet)


urlpatterns = [
    path('api-root/', include(router.urls), name='api-root'),
    path('personal_page/', views.personal_page, name='personal_page'),
    path('', views.ArticleIndexView.as_view(), name='index'),
    path('<int:tag_id>/', views.TagListView.as_view(), name='tag'),
    path('my_articles/', views.MyArticlesView.as_view(), name='my_articles'),
    path('<int:pk>', views.ArticleDetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.VoteResultView.as_view(), name='results'),
    path('article_like/<int:article_id>/<int:like>', views.article_like, name='article_like'),
    path('comment_like/<int:comment_id>/<int:like>', views.comment_like, name='comment_like'),
    path('<int:article_id>/vote/', views.vote, name='vote'),
    path('<int:article_id>/comment_create/', views.CommentCreate.as_view(), name='comment_create'),
    path('<int:article_id>/<int:comment_id>/comment_edit/', views.CommentCreate.as_view(), name='comment_edit'),
    path('<int:article_id>/<int:comment_id>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('add_article/', views.article_create_update_form, name='article_create'),
    path('add_article/create_article/', views.article_db_save, name='article_create_save'),
    path('edit_article/<int:article_id>', views.article_create_update_form, name='article_update'),
    path('edit_article/<int:article_id>/article_delete/', views.article_db_save, name='article_update_save'),
    path('search/', views.ArticleSearchView.as_view(), name='search'),
    path('delete_article/<int:article_id>', views.article_delete, name='article_delete'),
    path('<int:article_id>/publish_article/', views.publish_article, name='publish_article'),
    # path('froala_form', views.froala_form, name='froala_form'),
    # path('post_froala_form', views.post_froala_form, name='post_froala_form'),
    # path('froala_index', views.FroalaIndexView.as_view(), name='froala_index'),
    # path('froala/<int:pk>/', views.FroalaDetailMixinView.as_view(), name='froala_detail'),
    # path('ajax_demo/', views.AjaxHandlerView.as_view(), name='ajax_demo'),
    # path('ajax_page/', views.ajax_page, name='ajax_page'),
    # path('ajax_check/', views.AjaxDataCheck.as_view(), name='ajax_check')
]

djbook_test/apps/home/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('language_switch/<str:user_language>/', views.lang_switcher, name='lang'),
]

djbook_test/apps/weather/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.weather, name='index'),
    path('get_weather/', views.get_weather, name='get_weather')
]

djbook_test/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/articles/images/favicon.ico'), name='favicon'),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('articles/', include('articles.urls')),
    path('weather/', include('weather.urls')),
    path('', include('home.urls')),
    path('admin228/', admin.site.urls, name='admin'),
    path('account/', include('allauth.urls')),
    path('avatar/', include('avatar.urls')),
    path('api/drf-auth/', include('rest_framework.urls')),
    path('api/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
)

if 'rosetta' in settings.INSTALLED_APPS and settings.DEBUG:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

djbook_test/apps/articles/forms.py
from django import forms
from django.utils.translation import gettext as _
import re

from .models import Comment, Article


def cleanhtml(raw_html):
    clean_re = re.compile('<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});')
    cleantext = re.sub(clean_re, '', raw_html)
    return cleantext


def text_validator(origin_text: str, min_length: int = 0, max_length: int = 0):

    splitted_text: list = cleanhtml(origin_text.strip()).split()
    formated_text = ' '.join(splitted_text)
    if min_length:
        if not len(formated_text) >= min_length:
            return ''
    if max_length:
        if not len(formated_text) <= max_length:
            return ''
    if len(splitted_text) > 0 and not formated_text.isspace():
        return origin_text.strip()
    else:
        return ''


class CommentForm(forms.ModelForm):
    """Comments form"""

    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'cols': 45,
                                          'rows': 3,
                                          'minlength': 4,
                                          'maxlength': 300,
                                          'placeholder': _('Your comment...')})
        }
        labels = {
            'text': '',
        }


class ArticleEditForm(forms.ModelForm):
    """Add article form"""

    class Meta:
        model = Article
        fields = ('title', 'text')
        widgets = {
            'title': forms.TextInput(attrs={'minlength': 5,
                                            'maxlength': 200}),
            'text': forms.Textarea(attrs={'minlength': 10,
                                          'maxlength': 9000})
        }

djbook_test/apps/articles/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Prefetch
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.html import escape
from django.utils.translation import gettext_lazy as _
from django.views import generic
from django.views.generic.base import View

from .forms import CommentForm, ArticleEditForm, text_validator, cleanhtml
from .models import Article, Choice, Tag, Comment
# from .tasks import send_task, admin_send_task


########################################################################################################################
################################################ ARTICLE CRUD #########################################################
########################################################################################################################


@login_required()
def personal_page(request):
    return render(request, 'articles/personal_page.html')


@login_required()
def publish_article(request, article_id):
    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse_lazy('home:home'))
    article = get_object_or_404(Article, id=article_id)
    article.publish()
    # HttpResponseRedirect(reverse('articles:detail', args=(article_id,)))
    return redirect(request.META.get('HTTP_REFERER'))


class ArticleIndexView(generic.ListView):
    paginate_by = 16
    template_name = 'articles/article_list.html'

    # context_object_name = 'latest_article_list'
    def get_queryset(self):
        """
        Return the last published articles (not including those set to be
        published in the future).
        """
        if self.request.user.is_superuser:
            return Article.objects.only('title', 'is_published').all().order_by('-pub_date')
        else:
            return Article.objects.only('title').filter(is_published=True).order_by('-pub_date')


# ajax
class ArticleDetailView(generic.DetailView, generic.edit.FormView):
    model = Article
    template_name = 'articles/article_detail.html'
    form_class = CommentForm
    http_method_names = ['get']

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        comments = Comment.objects.filter(article_id=pk).select_related('user').order_by('-pub_date')
        return get_object_or_404(Article.objects.select_related(
            'user'
        ).prefetch_related(
            'tag', 'choice_set__vote_set__user', Prefetch('comment_set', queryset=comments)
        ), id=pk)


class ArticleSearchView(LoginRequiredMixin, generic.ListView):
    paginate_by = 16
    template_name = 'articles/article_list.html'
    context_object_name = 'search_list'

    def get_queryset(self):
        """
        Return the last published articles (not including those set to be
        published in the future).
        """
        valid_search = self.request.GET['search']
        if valid_search:
            return Article.objects.filter(title__icontains=valid_search, is_published=True).order_by('-pub_date')
        else:
            return HttpResponseRedirect(reverse_lazy('articles:home'))


@login_required()
def article_delete(request, article_id):
    user = request.user
    article = get_object_or_404(Article, id=article_id, user=user)
    article_title = article.title
    article.delete()
    my_article_list = Article.objects.filter(user=user).only('title').order_by('-pub_date')
    messages.success(request, _(f'Article "{article_title}" has been deleted'))
    return render(request, 'articles/article_list.html', {'my_article_list': my_article_list})


class MyArticlesView(LoginRequiredMixin, generic.ListView):
    paginate_by = 16
    template_name = 'articles/article_list.html'
    context_object_name = 'my_article_list'

    def get_queryset(self):
        """
        Return the last published articles (not including those set to be
        published in the future).
        """
        return Article.objects.filter(user=self.request.user).only('title').order_by('-pub_date')


@login_required()
def article_create_update_form(request, article_id=None):
    if article_id:
        article = get_object_or_404(Article.objects.select_related(
            'user'
        ).prefetch_related(
            'tag', 'choice_set'
        ), id=article_id)
        if article.user != request.user:
            return HttpResponseRedirect(reverse_lazy('articles:article_create'))
        form = ArticleEditForm(instance=article)
        return render(request, 'articles/article_edit.html', {
            'title': article.title,
            'choices': article.choice_set.all(),
            'tags': article.tag.all(),
            'article_id': article_id,
            'form': form
        })
    else:
        form = ArticleEditForm()
        return render(request, 'articles/article_edit.html', {
            'form': form,
            'article_id': article_id,
        })


@login_required
def article_db_save(request, article_id=None):
    """
    Request to save an article and its associated tags and voting from the form to the database
    """
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if not is_ajax:
        return HttpResponseRedirect(reverse_lazy('articles:article_create'))
    if article_id:
        article_model = get_object_or_404(Article, id=article_id, user=request.user)
        article_model.up_date = timezone.now()
        article_model.choice_set.all().delete()
    else:
        article_model = Article(user=request.user, up_date=None)
    data = ArticleEditForm(request.POST, instance=article_model)
    if not data.is_valid():
        return JsonResponse({'error': data.errors})
    data.save()

    tag_list, tag_status = add_article_list_validation(request, 'tag')
    choice_list, choice_status = add_article_list_validation(request, 'choice')

    if tag_status == 'error':
        return JsonResponse({'error': _(' • Tag should be the length between 2 and 200')})
    if choice_status == 'error':
        return JsonResponse({'error': _(' • Choice should be the length between 2 and 200')})
    if tag_list:
        existing_tags = set(Tag.objects.filter(name__in=tag_list))
        # existing_tag_names = set(tag.name for tag in existing_tags)

        new_tags_to_create = [Tag(name=tag) for tag in tag_list if tag not in existing_tags]

        # Save the new tags to the database
        Tag.objects.bulk_create(new_tags_to_create)

        # Fetch all tags again to include the newly created ones with primary keys
        all_tags = Tag.objects.filter(name__in=tag_list)
        # tags_to_add = list(existing_tags) + list(all_tags)
        article_model.tag.add(*all_tags)

    if choice_list:
        choices_to_create = [Choice(article_id=article_model.id, text=choice) for choice in choice_list]
        Choice.objects.bulk_create(choices_to_create)

    article_url = reverse_lazy('articles:detail', args=(article_model.id,))
    article_href = f'"<a href="{article_url}">{escape(article_model.title)}</a>"'
    article_url_message = _(f' • Article {article_href} successfully posted')

    #if not DEBUG:
    article_absolute_url = 'rodger-dj.herokuapp.com' + article_url
    html_content = render_to_string(
        'articles/email_template.html',
        {'article_url': article_absolute_url,
         'user': request.user.username,
         'article_title': article_model.title})
    # admin_send_task.delay(
    #     _(f'New article posted: {article_model.title}'),
    #     html_content,
    #     # article_model.user.email
    # )
    return JsonResponse({'success': article_url_message})


@login_required()
def article_like(request, article_id, like):
    article = get_object_or_404(Article.objects.select_related(
            'user'
        ).prefetch_related(
            'tag', 'choice_set__vote_set', 'comment_set__user'
        ), id=article_id)
    user = request.user
    like = bool(like)
    count = 1 if like else 0
    add_message = _('Liked') if like else _('Disliked')
    delete_message = _('Unliked') if like else _('Undisliked')
    try:
        existing_like = article.articlelike_set.get(user=user)
    except ObjectDoesNotExist:
        # first like/dislike
        message = add_message
        article.like_count += count
        article.articlelike_set.create(user=user, is_like=like)
        article.save()
    else:
        # like/dislike exist
        if existing_like.is_like != like:
            # existing like is different, change is_like value
            existing_like.is_like = like
            existing_like.save()
            article.like_count += count if like else -1
            article.save()
            message = add_message
        else:
            # existing like is same, delete like/dislike raw
            message = delete_message
            existing_like.delete()
            article.like_count -= count
            article.save()
    return JsonResponse({'success': message})


########################################################################################################################
################################################ COMMENT CRUD ##########################################################
########################################################################################################################


class CommentCreate(LoginRequiredMixin, View):
    def get(self, request, article_id, comment_id):
        comment = get_object_or_404(Comment.objects.select_related('user'), id=comment_id, user=request.user)
        article = get_object_or_404(Article.objects.select_related(
            'user'

djbook_test/apps/home/views.py
from os import getenv
from urllib.parse import urlparse, urlunparse

import ipinfo
from django.shortcuts import render, redirect
from django.utils.translation import activate
from .models import GuestData


def user_checker(address):
    access_token = getenv('ADDR_CHECK_API')
    handler = ipinfo.getHandler(access_token)
    details = handler.getDetails(address)
    return details.all


def get_address(request):
    if 'HTTP_X_FORWARDED_FOR' in request.META:
        address = request.META['HTTP_X_FORWARDED_FOR']
        return address
    else:
        return request.META['REMOTE_ADDR']


def home(request):
    user = request.user
    device_data = request.META
    address = get_address(request)
    address_data = user_checker(address)
    new = GuestData(user=user, device=device_data, address=address_data)
    new.save()
    return render(request, 'home/home_page.html')


def about(request):
    return render(request, 'home/about.html')


def lang_switcher(request, user_language):
    activate(user_language)
    # Redirect the user back to the previous page
    parsed_url = list(urlparse(request.META.get('HTTP_REFERER')))
    path_parts = parsed_url[2].split('/')
    path_parts[1] = user_language
    parsed_url[2] = '/'.join(path_parts)
    response = redirect(urlunparse(parsed_url))
    response.set_cookie('django_language', user_language)
    return response  # redirect(urlunparse(parsed_url))

djbook_test/templates/base.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html>
    <head>
    {% include 'head.html' %}
    {% block stylesheet %}
    {% endblock %}
    <title>
        {% block head_title %}
        {% endblock %}
    </title>
    {% block extra_head %}
    {% endblock %}
    </head>

<body>
{% block body %}
    {% include 'navbar.html' %}
    {% block content %}
        {% translate 'There is no any content' %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
    </body>
</html>
{% endblock %}
{% block script %}
{% endblock %}

djbook_test/templates/head.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.6.1.js"
            integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI="
            crossorigin="anonymous">
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous">
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@100;300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/thinline.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
          integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
</head>

djbook_test/templates/navbar.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href={% url 'home:home' %}>RODGER</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href={% url 'articles:index' %}>{% translate 'Articles' %}</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {% translate 'My Account' %}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            {% if user.is_superuser %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">{{ user.username }}</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'articles:personal_page' %}">{{ user.username }}</a></li>
                            {% endif %}
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'account_email' %}">{% translate 'Email settings' %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'account_logout' %}">{% translate 'LogOut' %}</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'articles:api-root' %}" target="_blank">{% translate 'API Root' %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'login' %}" target="_blank">{% translate 'Get API Key' %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}" target="_blank">{% translate 'Delete API KEY' %}</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'account_login' %}">{% translate 'LogIn' %}</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'account_signup' %}">{% translate 'Register Now' %}</a></li>
                        {% endif %}
                    </ul>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href='{% url 'articles:article_create' %}'>{% translate 'Add article' %} +</a>
                    </li>
                {% endif %}
                <a class="nav-link" href={% url 'home:about' %}>About</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ LANGUAGE_CODE }}
                    </a>
                    {% get_available_languages as languages %}
                    {% get_language_info_list for languages as lang_info %}
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for lang in lang_info %}
                            {% language lang.code %}
                                <li><a class="dropdown-item" href="{% url 'home:lang' lang.code %}">{{ lang.name_local }}</a></li>
                            {% endlanguage %}
                        {% endfor %}
                    </ul>
                </li>
            </ul>
            <form class="d-flex" action="{% url 'articles:search' %}" method="get">
                <input name="search" class="form-control me-2" type="search" minlength="3" placeholder={% translate "Search" %} aria-label="Search" required>
                <button class="btn btn-outline-success" type="submit">{% translate 'Search' %}</button>
                {{ search_message }}
            </form>
        </div>
    </div>
</nav>